# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Prefect image in which we install rs-client-libraries.
# Target Docker image names:
# ghcr.io/rs-python/prefect/rs-client-libraries/local
# ghcr.io/rs-python/prefect/rs-client-libraries/k8s
#

ARG PYTHON_VERSION=3.13.9
ARG PREFECT_TAG=3.6.5

# K8S image suffix: -k8s or empty
ARG K8S_IMAGE=xxx

FROM ghcr.io/rs-python/prefecthq/prefect:${PREFECT_TAG}-py${PYTHON_VERSION}${K8S_IMAGE}

COPY ./layer-cleanup.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh

ARG PREFECT_AWS_TAG=0.7.1

# Upgrande pip and install dependencies.
# NOTES:
#   - Install s3fs before boto3 to have a recent version
RUN pip install -U pip && \
    pip install \
        prefect-aws=="${PREFECT_AWS_TAG}" \
        s3fs \
        boto3 \
    && layer-cleanup.sh

# The CI builds the wheel packages, downloads them into ./whl/, then builds this Dockerfile from ./whl/,
# so the .whl files are under ./*.whl
RUN mkdir -p /tmp/whl
ADD ./*.whl /tmp/whl

# Install the rs-client-library wheel and opentelemetry instrumentation packages for dependencies
RUN pip install /tmp/whl/rs_client_libraries-*.whl && opentelemetry-bootstrap -a install && layer-cleanup.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-client-libraries"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-client-libraries/tree/develop/.github/dockerfiles/Dockerfile.prefect"
