# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This docker installs the rs-client-libraries wheel into the prefect docker image.
#

ARG PREFECT_TAG=xxx
# K8S image suffix: -kubernetes or empty
ARG K8S_IMAGE=xxx
FROM prefecthq/prefect:${PREFECT_TAG}-python3.11${K8S_IMAGE}

ARG DASK_TAG=xxx
ARG DASK_GATEWAY_TAG=xxx
ARG PREFECT_DASK_TAG=xxx

# Upgrande pip and install dependencies.
# NOTES:
#   - Install s3fs before boto3 to have a recent version
#   - We need the same numpy version as in eopf
RUN pip install -U pip && \
    pip install \
        dask[complete]=="${DASK_TAG}" \
        dask-gateway=="${DASK_GATEWAY_TAG}" \
        prefect-dask=="${PREFECT_DASK_TAG}" \
        prefect-aws \
        s3fs \
        boto3 \
        numpy=="1.26.4"

# The CI builds the wheel packages, downloads them into ./whl/, then builds this Dockerfile from ./whl/,
# so the .whl files are under ./*.whl
RUN mkdir -p /tmp/whl
ADD ./*.whl /tmp/whl

# Install the rs-client-library wheel and opentelemetry instrumentation packages for dependencies
RUN pip install /tmp/whl/*.whl && opentelemetry-bootstrap -a install

# Clean everything
RUN rm -rf /tmp/whl ~/.cache/pip /var/cache/apt/archives /var/lib/apt/lists/*

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-client-libraries"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/prefect/rs-client-libraries/local;ghcr.io/rs-python/prefect/rs-client-libraries/k8s"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-client-libraries/tree/develop/.github/dockerfiles/Dockerfile.prefect"

LABEL org.opencontainers.image.description="prefect image in which we installed dask and the rs-client-libraries wheel package."
