# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This docker installs the rs-client-libraries wheel
# in the jupyter docker image that is used by rs-demo in local mode.

#
# Jupyter image for local mode in which we install prefect and rs-client-libraries.
# Target Docker image name:
# ghcr.io/rs-python/jupyter/rs-client-libraries/local
#

ARG PYTHON_VERSION=3.13.9
ARG JUPYTER_HUB_VERSION=5.4.2

FROM ghcr.io/rs-python/quay.io/jupyter/base-notebook:hub-${JUPYTER_HUB_VERSION}-py${PYTHON_VERSION}

USER root

COPY ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh && layer-cleanup.sh

# We need psycopg2 to debug from Jupyter in some demos
RUN \
    restore-apt.sh && \
    apt update && apt install -y libpq-dev gcc && \
    pip install psycopg2 && \
    apt autoremove -y gcc && \
    layer-cleanup.sh

# The CI builds the wheel packages, downloads them into ./whl/, then builds this Dockerfile from ./whl/,
# so the .whl files are under ./*.whl
RUN mkdir -p /tmp/whl
ADD ./*.whl /tmp/whl

# Install the rs-client-library wheel and opentelemetry instrumentation packages for dependencies
RUN pip install --no-cache-dir /tmp/whl/rs_client_libraries-*.whl && opentelemetry-bootstrap -a install && \
    layer-cleanup.sh

# Install other useful dependencies for rs-demo in local mode.
RUN pip install --no-cache-dir papermill && layer-cleanup.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

USER jovyan

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-client-libraries"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-client-libraries/tree/develop/.github/dockerfiles/Dockerfile.jupyter"
