name: Generate documentation

# TODO: when to generate the doc ?
# For now, only for new git tags (including hierarchical tags like v1.0/beta), or manually
on:
    push:
      tags:
        - '**'
    workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

jobs:

  generate-documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish the generated documentation
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poetry-install
        with:
          working-directory: .
      # The technical documentation uses a dedicated python project to be built
      - uses: ./.github/actions/poetry-install
        with:
          working-directory: ./docs

      # The order of these steps is important
      # The technical documentation has to be first
      # because some fake documentation are then replaced
      # by the following steps for link purpose.

      - name: Generate AsciiDoc HTML documentation
        run: |
          set -x
          sudo apt-get update && sudo apt-get install -y asciidoctor # install asciidoctor
          poetry run asciidoxy --base-dir doc --build-dir ../dist/doc/ --multipage index.adoc
        working-directory: ./docs
        shell: bash

      - name: Generate Python API HTML documentation from the docstrings
        run: |
          set -x

          # Generate rst files from docstrings
          poetry run sphinx-apidoc -o docs/rs_workflows/generated/common rs_workflows/

          # Generate Python API html from rst files
          # TODO ?
          # poetry run sphinx-build -M html docs/rs_workflows dist/doc/output/api/python/

      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist/doc/output

      - run: >
          echo "Documentation published to: https://rs-python.github.io/rs-client-libraries" >> $GITHUB_STEP_SUMMARY
