name: Publish wheels and Docker images

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: Tag the docker images as e.g. 'latest' or 'feat-rspy123'
        required: false
        default: latest

# workflow_dispatch must be set in the main branch, see: https://stackoverflow.com/a/71423764
jobs:
  test-workflow-dispatch-3:
    runs-on: ubuntu-latest
    name: Test workflow_dispatch in publish.yml
    steps:
      - run: echo Test workflow_dispatch in publish.yml
        shell: bash